repos:
    - repo: https://github.com/gitguardian/ggshield
      rev: v1.53.0
      hooks:
          - id: ggshield
            language_version: python3
            stages: [pre-commit]

    - repo: local
      hooks:
          - id: prettier
            name: prettier (npx)
            entry: npx prettier --write
            language: system
            files: '\.(js|json|ya?ml|md)$'
            exclude: |
                (?x)^(
                    .github/.*|
                    CHANGELOG.md|
                    docs/.*|
                    sea-prep.blob|
                    build.cjs
                )$
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0 # Use the ref you want to point at
      hooks:
          - id: check-case-conflict
          - id: check-json
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
